# Generated by Django 5.2.13 on 2026-04-22 11:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('RU', 'Russian'), ('EN', 'English'), ('CRL', 'Cyrillic'), ('UZ', 'Uzbek')], default='EN', max_length=5)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.CharField(db_index=True, help_text='App version number (e.g., 1.0.0)', max_length=20, unique=True)),
                ('release_date', models.DateField(blank=True, help_text='When this app version was released', null=True)),
                ('changelog', models.TextField(blank=True, help_text='Changelog or release notes for this version', null=True)),
            ],
            options={
                'verbose_name': 'App Version',
                'verbose_name_plural': 'App Versions',
                'db_table': 'app_versions',
                'ordering': ['-release_date', '-created_at'],
                'indexes': [models.Index(fields=['version_number'], name='app_version_number_idx'), models.Index(fields=['release_date'], name='app_version_release_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_model', models.CharField(db_index=True, max_length=255)),
                ('operation_version', models.CharField(max_length=155)),
                ('device_type', models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'Android'), ('ALL', 'ALL')], db_index=True, default='ANDROID', max_length=7)),
                ('device_id', models.CharField(db_index=True, help_text='Unique device identifier (UUID from mobile app)', max_length=255)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the device', validators=[django.core.validators.validate_ipv46_address])),
                ('last_login', models.DateTimeField(auto_now=True, db_index=True)),
                ('first_login', models.DateTimeField(auto_now_add=True)),
                ('visit_location', models.JSONField(blank=True, help_text='Geographic location data', null=True)),
                ('language', models.CharField(choices=[('RU', 'Russian'), ('EN', 'English'), ('CRL', 'Cyrillic'), ('UZ', 'Uzbek')], default='CRL', max_length=3)),
                ('theme', models.CharField(choices=[('DARK', 'Dark'), ('LIGHT', 'Light')], default='LIGHT', max_length=5)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Device session is active')),
                ('is_push_notification', models.BooleanField(default=True, verbose_name='Push Notifications Enabled')),
                ('is_auth_password', models.BooleanField(default=False, verbose_name='Biometric Authentication Enabled')),
                ('refresh_token_jti', models.CharField(db_index=True, help_text='JWT refresh token JTI (JWT ID) for this device session', max_length=255, unique=True)),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, db_index=True, help_text='When the refresh token expires', null=True)),
                ('logged_out_at', models.DateTimeField(blank=True, help_text='When user logged out from this device', null=True)),
                ('firebase_token', models.CharField(blank=True, db_index=True, max_length=500, null=True, unique=True)),
                ('app_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='users.appversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'devices',
                'ordering': ['-last_login'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.permission')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(help_text='e.g., /api/products/ or /api/users/{id}/', max_length=255)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('name', models.CharField(help_text='Human readable name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('authenticated', 'Authenticated'), ('permission', 'Permission Required')], db_index=True, default='permission', help_text='Access control type for this endpoint', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('permission', models.ForeignKey(help_text='Permission required to access this endpoint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoints', to='users.permission')),
            ],
            options={
                'ordering': ['path', 'method'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('permissions', models.ManyToManyField(related_name='roles', to='users.permission')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='users.role'),
        ),
        migrations.CreateModel(
            name='TokenBlocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jti', models.CharField(db_index=True, help_text='JWT ID (jti claim) of the access token', max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When the access token expires naturally (for auto-cleanup)')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, help_text='When the token was added to blocklist')),
                ('reason', models.CharField(default='logout', help_text='Reason for blocking (logout, password_change, etc.)', max_length=50)),
                ('device', models.ForeignKey(blank=True, help_text='Device this token was issued to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_tokens', to='users.device')),
                ('user', models.ForeignKey(blank=True, help_text='User this token was issued to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blocked Token',
                'verbose_name_plural': 'Blocked Tokens',
                'db_table': 'token_blocklist',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='users.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions_direct', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=6)),
                ('expiration_seconds', models.PositiveSmallIntegerField(default=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Code',
                'verbose_name_plural': 'Verification Codes',
                'db_table': 'verification_codes',
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'is_active'], name='device_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_id', 'device_type'], name='device_id_type_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['refresh_token_jti', 'is_active'], name='device_token_active_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['-last_login'], name='device_last_login_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['refresh_token_jti', 'is_active', 'refresh_token_expires_at'], name='device_token_validation_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='endpoint',
            unique_together={('path', 'method')},
        ),
        migrations.AddIndex(
            model_name='tokenblocklist',
            index=models.Index(fields=['jti', 'expires_at'], name='blocklist_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenblocklist',
            index=models.Index(fields=['expires_at'], name='blocklist_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenblocklist',
            index=models.Index(fields=['user', '-blocked_at'], name='blocklist_user_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user', 'is_active'], name='users_userp_user_id_eb3c30_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['is_active'], name='users_userp_is_acti_7b9708_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('user', 'permission')},
        ),
    ]
